version: '3'

volumes:
  result:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volume/result
  log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volume/log
  apache:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volume/apache

services:
  vas-1.3.1:
    image: hieucien/vas:1.3.1
    container_name: vas-1.3.1
    hostname: vas-1.3.1
    restart: always
    ports:
      - '4173:4173'
      - '4174:4174'
      - '4175:4175'
    volumes:
      - result:/var/www/evolution/public/result
      - log:/var/www/evolution/public/log
      - apache:/var/log/apache2
