volumes:
  result:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volume/result
  upload:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volume/upload
  log:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volume/log
  apache:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volume/apache

services:
  vas-1.0.7:
    image: hieucien/vas:1.0.7
    container_name: vas-1.0.7
    hostname: vas-1.0.7
    restart: always
    ports:
      - '4173:4173'
      - '4174:4174'
      - '4175:4175'
    volumes:
      - result:/var/www/server/public/result
      - upload:/var/www/server/public/upload
      - log:/var/www/server/public/log
      - apache:/var/log/apache2
